In [81]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('laptops.csv')

In [4]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [5]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [6]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [7]:
df.isnull()

Laptop  Status  Brand  Model    CPU    RAM  Storage  Storage type  \
0      False   False  False  False  False  False    False         False   
1      False   False  False  False  False  False    False         False   
2      False   False  False  False  False  False    False         False   
3      False   False  False  False  False  False    False         False   
4      False   False  False  False  False  False    False         False   
...      ...     ...    ...    ...    ...    ...      ...           ...   
2155   False   False  False  False  False  False    False         False   
2156   False   False  False  False  False  False    False         False   
2157   False   False  False  False  False  False    False         False   
2158   False   False  False  False  False  False    False         False   
2159   False   False  False  False  False  False    False         False   

        GPU  Screen  Touch  Final Price  
0      True   False  False        False  
1      True   False  False        False  
2      True   False  False        False  
3     False   False  False        False  
4      True   False  False        False  
...     ...     ...    ...          ...  
2155  False   False  False        False  
2156  False   False  False        False  
2157  False   False  False        False  
2158   True   False  False        False  
2159   True   False  False        False  

[2160 rows x 12 columns]

In [8]:
df['Final Price'].max()

7150.47

In [9]:
df.describe().round()

RAM  Storage  Screen  Final Price
count  2160.0   2160.0  2156.0       2160.0
mean     15.0    596.0    15.0       1313.0
std      10.0    361.0     1.0        911.0
min       4.0      0.0    10.0        201.0
25%       8.0    256.0    14.0        661.0
50%      16.0    512.0    16.0       1032.0
75%      16.0   1000.0    16.0       1709.0
max     128.0   4000.0    18.0       7150.0

In [10]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [11]:
df.Brand

0         Asus
1       Alurin
2         Asus
3          MSI
4           HP
         ...  
2155     Razer
2156     Razer
2157     Razer
2158     Razer
2159     Razer
Name: Brand, Length: 2160, dtype: object

In [12]:
df.groupby('Brand').max('Final Price')

RAM  Storage  Screen  Final Price
Brand                                              
Acer               32     1000    17.3      3691.00
Alurin             16      512    15.6       869.00
Apple              32     2000    16.2      3849.00
Asus               64     4000    18.0      5758.14
Deep Gaming        64     2000    17.3      1639.01
Dell               32     1000    17.0      3936.00
Denver              4      256    14.0       329.95
Dynabook Toshiba   16      512    15.6      1805.01
Gigabyte           32     2000    17.3      3799.00
HP                 32     1000    17.3      5368.77
Innjoo              8      512    15.6       431.38
Jetwing             8      256    15.6       469.27
LG                 32     2000    17.0      2399.00
Lenovo             32     2000    17.3      5018.14
MSI               128     2000    17.3      7150.47
Medion             32     2000    17.3      3799.00
Microsoft          32     2000    15.0      3747.91
Millenium          16      500    15.6      2312.71
PcCom              32     1000    17.3      1949.90
Primux              8      512    15.6       599.41
Prixton             4      128    15.6       329.95
Razer              32     2000    17.3      4999.01
Realme              8      512    14.0       999.00
Samsung            32     1000    16.0      3699.01
Thomson             8      512    15.6       436.56
Toshiba             8      256    14.0       799.00
Vant               40     1000    14.0      1217.01

In [13]:
df.describe()

RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [14]:
median_value_screen = df.Screen.median()

In [15]:
median_value_screen

15.6

In [16]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [17]:
mode_value_screen = df.Screen.mode()

In [51]:
mode_value_screen[0]

15.6

In [68]:
df['Screen'] = df['Screen'].fillna(mode_value_screen[0])

In [69]:
df['Screen'].isnull().sum()

0

In [70]:
df.Screen.median()

15.6

In [80]:
df[df.Brand == 'Innjoo'][['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [89]:
X = df[df.Brand == 'Innjoo'][['RAM','Storage','Screen']].to_numpy()

In [90]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [92]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [111]:
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [112]:
I_XTX = np.linalg.inv(XTX)
I_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [113]:
XTX.dot(I_XTX)

array([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.11022302e-16, 1.00000000e+00]])

In [116]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [117]:
w = (I_XTX.dot(X.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [118]:
w.sum()

91.29988062995588